FORMAT: 1A
HOST: https://sense-sense-api.herokuapp.com

# Sensei Sense

Sensei Sense is the best MasterMind derivative in the world

## Authentication

*Sense Sense API* uses token authentication. Your token can be any text you wish. As long as you use the same token between requests, you'll have access to the same list items.

# Game

## Game [/games?access_token]

Creates a new game

+ Parameters

    + access_token: "illustriousvoyage" (string) - Your unique access token

### Create [POST]

+ Response 200 (application/json)

            [
              "id": 1,
              "moves" : []
            ]

## Move [/games/move?access_token&game_id]

### Make a Move [POST]

You may create new move using this action. It takes a JSON object containing the Guess.

+ Request (application/json)

            {
              "guess": ["Red", "Green", "Blue", "Orange"]
            }

+ Response 201 (application/json)

    + Headers

    + Body

            [
              "id": 1,
              "moves": [
                {
                  "guess": ["Red", "Green", "Blue", "Orange"],
                  "result": ["exact match", "inexact_match", "miss", "miss"]
                },
                {
                  "guess": ["Blue", "Green", "Blue", "Orange"],
                  "result": ["exact match", "inexact_match", "miss", "miss"]
                }
              ]
            ]

# Data Structures

## Game (object)

+ id (required, number) - The id of this game
+ moves (required, array) - Array of moves

## Move (object)

+ guess (required, array) - The list of four color guesses
+ result (required, array) - The list of four results (exact_match, inexact_match, miss)
